// Real Google reviews curated from Beautymanntra's listing (4.6 ★ · 1,012 reviews).
// Names, snippets and timeframes are from the public review feed.
export const REAL_REVIEWS = [
  {
    name: "Janika Nilesh Fulsunge",
    when: "2 months ago",
    rating: 5,
    service: "Massage · Manicure",
    text: "I had a very good experience with the treatment. Sangeeta didi was skilled and attentive, doing an excellent job with both the massage and manicure. Would definitely recommend.",
  },
  {
    name: "Vidhi Patel",
    when: "2 months ago",
    rating: 5,
    service: "General",
    text: "Less time & great results — absolutely skilled staff, did their work perfectly in no time.",
  },
  {
    name: "Sangita Valand",
    when: "8 months ago",
    rating: 5,
    service: "Haircut · Hair Treatment",
    text: "I had my haircut & hair treatment with Rutvik last week and he is amazing! He listens carefully and gives great advice. We have already booked our next appointments.",
  },
  {
    name: "Arpita Valand",
    when: "8 months ago",
    rating: 5,
    service: "Hair Styling",
    text: "Excellent service!!! Friendly and engaging staff, very professional. I would 100% recommend this salon. Rutvik is a very passionate stylist.",
  },
  {
    name: "Faith Tharakan",
    when: "8 months ago",
    rating: 5,
    service: "General",
    text: "Very nice services, and excellent management — it was truly worth it for the money and I highly recommend coming here.",
  },
  {
    name: "Pramod Kumar",
    when: "a year ago",
    rating: 5,
    service: "Hair · Complete Salon",
    text: "Amazing place for a complete salon experience! My hairdresser, Harsh, instantly understood what I wanted and delivered beyond expectations.",
  },
  {
    name: "Tejas Patil",
    when: "a year ago",
    rating: 5,
    service: "Haircut",
    text: "I had a wonderful experience at Beautymanntra! The stylist suggested some great options based on my face shape, and the end result was just what I wanted.",
  },
  {
    name: "Nidhi Priya",
    when: "a year ago",
    rating: 5,
    service: "Hair · Styling",
    text: "Received awesome service. Rohan, the brand manager, is very knowledgeable and professional. He attends to the customer with full dedication and care.",
  },
  {
    name: "Meghna Patel",
    when: "Local Guide · 6 yrs ago",
    rating: 5,
    service: "Hair Colour · Keratin",
    text: "I had my hair colour and keratin treatment done by Mr. Subhash. He did a great job. Loved the results — great service and friendly staff!",
  },
  {
    name: "Priyanshi Bhatt",
    when: "8 months ago",
    rating: 5,
    service: "Haircut",
    text: "I got my haircut done and it was a great experience with Rohan and team. I would look forward to visit again. ❤️",
  },
  {
    name: "Sofia Sindhi",
    when: "a year ago",
    rating: 5,
    service: "Hair · Skin",
    text: "Amazing services and very polite staff. Been there for hair and skin treatments and am pretty much satisfied. Would surely visit again. Keep it up!",
  },
  {
    name: "Dipika Bhojani",
    when: "2 months ago",
    rating: 5,
    service: "General",
    text: "Very nice service by Sangeeta ji.",
  },
  {
    name: "Tathya Mankad",
    when: "2 months ago",
    rating: 5,
    service: "General",
    text: "Very good service and respectful members.",
  },
  {
    name: "Nishi Jivarani",
    when: "a year ago",
    rating: 5,
    service: "General",
    text: "I had a great experience with Mrs. Manisha — she is very efficient in her work, having good skills and being very precise. She looked after my requirements patiently.",
  },
  {
    name: "Kwisha Shah",
    when: "2 yrs ago (revisited 2024)",
    rating: 5,
    service: "Multi-service",
    text: "Went to Beautymanntra again for the same services and we're delighted. Thanks to Khushi, Sanuj, Rahul, Neha, and Rohan. Nice experience!",
  },
  {
    name: "Naima Patel",
    when: "a year ago",
    rating: 5,
    service: "General",
    text: "Great experience! The staff were friendly and made me feel really comfortable. Excellent service. Highly recommend!",
  },
  {
    name: "Dhara Parikh",
    when: "Local Guide · 3 yrs ago",
    rating: 5,
    service: "Aromatherapy · Pedicure",
    text: "Thanks Beauty Mantra for pampering me with great love. Aromatherapy massage was relaxing and hygienic. Pedicure and anti-tan were very effective.",
  },
  {
    name: "Lehmina Sindhi",
    when: "a year ago",
    rating: 5,
    service: "Multi-service",
    text: "Wonderful experience — very nice service, well-dressed and well-behaved staff. Used the very best products for skin & hair. Superb experience — 9.5 out of 10.",
  },
  {
    name: "Dhara Prajapati",
    when: "a year ago",
    rating: 5,
    service: "Hair",
    text: "I am very thankful to Rohan sir and their team for providing such an enriching experience for the betterment of my hair. Don't miss the opportunity to visit Beauty Mantra.",
  },
  {
    name: "Priyanka Shah",
    when: "8 months ago",
    rating: 5,
    service: "General",
    text: "Awesome service and amazing professionalism. It's always a pleasure to be around and get service done here. Keep up the good work, Team.",
  },
  {
    name: "Richa Roy",
    when: "2 yrs ago",
    rating: 5,
    service: "Balayage",
    text: "I got my balayage natural highlights done for the very first time and I am in love with my hair. Definitely recommending this salon for their services!",
  },
  {
    name: "Hena Prajapati",
    when: "2 yrs ago",
    rating: 5,
    service: "Long-time client",
    text: "I have been at Beauty Mantra for the past 3 years and I am amazed by their services and especially with the staff — well-behaved and experienced professionals.",
  },
  {
    name: "Kajal Gohil",
    when: "6 yrs ago",
    rating: 5,
    service: "Keratin · Haircut",
    text: "Went for the first time to this branch for hair keratin and haircut which was excellent. The staff is polite, professional and well-mannered. Thanks Subhash — outstanding.",
  },
  {
    name: "Ishangi Shah",
    when: "Local Guide · 8 yrs ago",
    rating: 5,
    service: "General",
    text: "Very professional staff and great services. It's a pleasure to be here among the friendly and talented staff. They guide you based on your beauty goals.",
  },
  {
    name: "Asha Bariya",
    when: "2 months ago",
    rating: 5,
    service: "Haircut",
    text: "So nice haircut by Harshil.",
  },
  {
    name: "Hiren",
    when: "Local Guide · 3 yrs ago",
    rating: 5,
    service: "Hair · Salon",
    text: "I was a regular customer of a famous salon of Vadodara, but once I tried Beauty Mantra I really got impressed and fond of it. The way of greeting, their hair artists, the products they use — simply awesome.",
  },
  {
    name: "V. S.",
    when: "Local Guide · 3 yrs ago",
    rating: 5,
    service: "Haircut · Colour",
    text: "I got my haircut, hair colour and hair treatment done recently. Rohan was the whole idea behind my look. Got my haircut after 2 years and it was the best haircut by Rohan.",
  },
  {
    name: "Vibhuti Patel",
    when: "Local Guide · a year ago",
    rating: 5,
    service: "Multi-service",
    text: "Rohan, Neha Saroj and Kalpana did well. Rohan's management is extremely good — I am delighted to have my services done under his management.",
  },
  {
    name: "Reni Jinu",
    when: "3 yrs ago",
    rating: 5,
    service: "Haircut",
    text: "Superb haircut by Asif — amazing hair stylist. The special care and hygiene is next level. One should always opt for Beauty Mantra — once you come here you won't go to another salon. ❤️🔥",
  },
  {
    name: "Sujata Patil",
    when: "3 yrs ago",
    rating: 5,
    service: "Facial · Under-eye",
    text: "Very satisfying Aqua-therm facial and under-eye treatment from Sweety. She kept my eye sensitivity in mind. Her hand movements are thorough and soothing.",
  },
  {
    name: "Vaishakhi Shah",
    when: "8 months ago",
    rating: 5,
    service: "General",
    text: "Amazing experience. Well-trained staff and fabulous service.",
  },
  {
    name: "Dishali Shah",
    when: "3 yrs ago",
    rating: 5,
    service: "Scalp Treatment",
    text: "The scalp treatment is amazing. They offered an amazing response and treatment. I feel loved again — thanks Beauty Mantra salon for this magical experience.",
  },
  {
    name: "Shivani Pandya",
    when: "Local Guide · 8 yrs ago",
    rating: 5,
    service: "General",
    text: "I really don't like going to beauty salons but I'm very happy at Beauty Mantra — warm, friendly, yet very professional service. The treatment room is spotlessly clean.",
  },
  {
    name: "Tithi Shukla",
    when: "Local Guide · 5 yrs ago",
    rating: 5,
    service: "Hair · Long-time",
    text: "My mum and I have been regulars at this salon for a long time. Mrs. Bijal and her team take such good care of us — Nikunj did an amazing job on our hair.",
  },
  {
    name: "Aquesha Tirmizi",
    when: "Local Guide · 3 yrs ago",
    rating: 5,
    service: "Hair",
    text: "Anjuman is a 'mind reader' — she exactly knows what the client wants. Brilliant experience and best result. Staff is very friendly and advises best hair care tips.",
  },
  {
    name: "Himani Thanki",
    when: "Local Guide · 6 yrs ago",
    rating: 5,
    service: "Balayage",
    text: "Subhash made me understand the service he was suggesting and recreated the exact look I wanted by hand-painting my hair — using the balayage technique. 5 stars.",
  },
  {
    name: "Simran Thanki",
    when: "5 yrs ago",
    rating: 5,
    service: "Hair",
    text: "First experience with Beautymanntra. Ms. Shivani did a great job on my hair — well trained and talented. Staff in general was so sweet and polite, and the place was very hygienic.",
  },
  {
    name: "Elisha Pope",
    when: "3 yrs ago",
    rating: 5,
    service: "Haircut",
    text: "I had a haircut at Beauty Mantra, Vasna by Mr. Asif who was very polite and professional with his work. He really did a great job — this place offers great service.",
  },
  {
    name: "Khushbu Patel",
    when: "a year ago",
    rating: 5,
    service: "General",
    text: "Thank you Harshil for your wonderful service. I totally recommend Beauty Mantra Salon — they provide very good service.",
  },
  {
    name: "Dhvani Patel",
    when: "a year ago",
    rating: 5,
    service: "General",
    text: "Really very good salon in Vadodara. I'll go decently for a second time. Special thanks to Mr. Harshil — literally very good experience. 🫶🏻",
  },
  {
    name: "Mehfuza Pathan",
    when: "5 yrs ago",
    rating: 5,
    service: "Hair Smoothening",
    text: "Did hair smoothening and the result was awesome. They have regular offers which are again good. Overall nice experience at Vasna, Vadodara.",
  },
  {
    name: "Ayushi Walia",
    when: "6 yrs ago",
    rating: 5,
    service: "Keratin",
    text: "First experience and they give the best services. Subhash was with me and my mother for the keratin treatment — totally worth it!",
  },
  {
    name: "Divyangi Desai",
    when: "3 yrs ago",
    rating: 5,
    service: "Bridal",
    text: "I had awesome services. I approached them for bridal services and they served the best they can — with all heart.",
  },
  {
    name: "Charmy Shah",
    when: "Local Guide · 6 yrs ago",
    rating: 5,
    service: "Keratin",
    text: "Did keratin treatment with Miss Kashi. She is amazing — has done the entire treatment whole-heartedly with patience. Loved her and definitely will recommend her.",
  },
  {
    name: "Ekta Kapadia",
    when: "6 yrs ago",
    rating: 5,
    service: "Premium Keratin · Manicure · Facial",
    text: "Extremely satisfying experience. Done premium keratin treatment, manicure, facial and a couple of other services — very cooperating staff!",
  },
];
